// Static operating guide for the meta-flow: how to change the system of work.
// Universal — the procedure does not depend on a board's stages — so init drops
// it into .kanbento/ as a fixed asset (unlike AGENTS.md, which is compiled per
// board). Built as an array so inline `code` backticks need no escaping.

export const EVOLVING_MD = [
  '# Evolving this board',
  '',
  'Changing the *system of work* — adding a stage, tightening a WIP limit, adding',
  'a gate or a card type — is itself work: you edit the board source under',
  '`.kanbento/` and recompile. It is **not** a plain file edit. In-flight cards may',
  'be left in a stage that no longer exists, so a structure change is a transaction',
  'that must be reconciled.',
  '',
  '## When to change it (usually: don’t)',
  '',
  'Structure earns its place — add it when the flow demands it, not on a hunch:',
  '',
  '- **recurrence** — a card *type* once N cards behave alike, or a *relation* type once an edge label recurs',
  '- **failure** — a review/gate where cards keep bouncing',
  '- **contention** — a WIP limit where concurrency measurably hurt cycle time',
  '',
  'A bare pool that just accumulates Options is a fine resting state. Don’t add a',
  'commitment point or stages speculatively — an empty pipeline is pure overhead.',
  'The board will not nag you to grow; grow when the evidence is in.',
  '',
  '## How to change it (the transaction)',
  '',
  '1. **Edit** `.kanbento/manifest.*` — add/rename/remove a stage, change a `wip`,',
  '   add an `entry` gate, add a `type`.',
  '2. **Preview** — `kanbento diff`: the structural changeset, and *which in-flight',
  '   cards get re-placed*. (After a bare edit, `BOARD.md` also lists stranded cards',
  '   under **⚠ Orphaned**.)',
  '3. **Apply** — `kanbento reconcile`: records a `StructureMutated` event, re-places',
  '   orphaned cards, re-baselines `compiled.json`, and regenerates this guide and',
  '   `AGENTS.md`. The board is consistent again.',
  '',
  'Never edit the manifest and keep working — you would leave orphaned cards and a',
  'stale baseline. Edit → diff → reconcile is one move.',
  '',
  '## The manifest',
  '',
  '`.kanbento/manifest.*` (JSON or YAML) describes the board. The flow engine only',
  'requires each stage’s `role` — a closed vocabulary; everything else is open:',
  '',
  '| role | meaning |',
  '|------|---------|',
  '| `options` | uncommitted, discardable (the inbox / pool) |',
  '| `commit` | the commitment point; its `entry` gate is the Definition of Ready |',
  '| `active` | committed work in progress |',
  '| `loop` | a checkpoint with a feedback edge back (review / QA) |',
  '| `done` | the delivery point; its `entry` gate is the Definition of Done |',
  '',
  'Stages are ordered; forward flow is implied by that order. Only non-forward',
  'edges (loop-backs, skips) go in `flows`. `wip` is optional per stage. A stage may',
  'declare `entry`/`exit` criteria (its DoR / DoD) inline as RFC 2119 pairs —',
  '`[[MUST, "..."], [SHOULD, "..."]]` — judged independently on the way in and the',
  'forward way out (only an explicit MUST blocks; a keyword-less criterion is open',
  'for interpretation, not enforced). The fuller form is an `agreement`: a',
  "Ready(DoR)·Body·Done(DoD) markdown contract with a prose body (the agent's),",
  'judged the same way — reach for it when a body or examples earn a doc. A stage',
  'may also point a `procedure` at a knowledge artifact (its execution instructions),',
  'surfaced as a resolved path on entry. WIP capacity is the one computed gate,',
  'enforced inline on every transition.',
  '',
  'For the authoritative grammar — the closed core plus the facet skeleton — run',
  '`kanbento schema`. Do not copy a manifest from memory; it drifts from the spec.',
  '',
  '## A type can grow a lifecycle',
  '',
  'Instantiation is already a state. The moment prose becomes a *file* it exists, and',
  'existence is itself a state — just an undefined one; there is no stateless record.',
  'So the gradient is not about *acquiring* a state (that happens at birth) but about',
  '*structuring the state-space*:',
  '',
  '- **implicit** — instantiated, state undefined (you might scribble `status: shipping`,',
  '  but ad hoc — not yet a vocabulary);',
  '- **a defined vocabulary** — `status: { values: { idea: "…", active: "…" } }`:',
  '  the states are *named and described* (a proto-flow), checked at read. The',
  '  descriptions are advisory — agents reason from them, nothing is gated yet — and a',
  '  vocabulary reused across types can be lifted to a top-level `vocabularies` block',
  '  and referenced (`$ref`), defined once;',
  '- **a flow** — the states gain order, transitions, and gates, and the type starts',
  '  *moving* (drop `flow: false`).',
  '',
  '(A card is the same shape with the flow already on: existence just lands it in the',
  'first stage.) The state is there from birth; defining the *vocabulary* is cheap; the',
  'transition machinery is the expensive part — add it only when the states need',
  'policing. So define the states long before the flow.',
  '',
  '## The same ramp on every axis',
  '',
  'That lifecycle is one face of a single rule — *start where you are, tighten as it is',
  'earned*. The same ramp runs through the rest, which is exactly why structure is never',
  'imposed up front:',
  '',
  '- **enforcement** — advisory → strict;',
  '- **a type** — existence → a status vocabulary → a flow;',
  '- **chaos → order** — prose → a file → structure → a flow;',
  '- **a reference** — a bare path in prose → `file:path` (a real, lint-guarded edge)',
  '  → a typed CURIE (`type:slug`) once the target earns a type;',
  '- **a relation** — an open key → a declared type (inverse / symmetric / range / cardinality)',
  '  → a strict vocabulary (`policies.relations: strict`); typing is a read-overlay, so it is retroactive;',
  '- **the graph** — a dangling ref → the frontier → a researched record;',
  '- **validation** — `lint` (read-only, advisory) → wired to a boundary you choose.',
  '',
  'Every rung is reached when the evidence is in, never on a hunch — so starting loose',
  'costs nothing: the path you scribble today becomes a typed edge tomorrow with its',
  'references intact, the way a bare pool becomes a pipeline only when the flow earns',
  'it. Evolve the structure; do not pre-build it.',
  '',
  '## How conflicts resolve (defaults)',
  '',
  '| change | resolution |',
  '|--------|------------|',
  '| stage **added** | nothing to do |',
  '| stage **renamed** | cards follow to the new id |',
  '| stage **removed** | cards re-enter at the **first stage** |',
  '| **WIP** tightened below current count | grandfathered; stop admitting until it drains |',
  '| **gate** strengthened | already-crossed cards grandfathered; new crossings use it |',
  '| **type** removed | cards revert to unclassified |',
  '',
  'Nothing is destroyed: state is a replay of an immutable log, so every change is',
  'reversible (append the inverse) and the re-placements are ordinary, audited',
  'move events.',
  '',
  '## Who changes it',
  '',
  'Agents **propose** structure changes with evidence (flow metrics, reflections);',
  'a human holds the structural gate. The board can rewrite its own rules, so the',
  'reflexive edge stays human-curated for now.',
  '',
  '## Upgrading the tooling (tactical)',
  '',
  'Distinct from evolving the *process* above: now and then the **kanbento tool**',
  'itself moves on (a release — `brew upgrade kanbento` / `npm i -g kanbento`), and a',
  'board’s generated artifacts fall behind. That is housekeeping, not a process change:',
  '',
  '- `kanbento --version` — what you have; a board’s `compiled.json` records the',
  '  `toolVersion` that last built it.',
  '- `kanbento upgrade [--dry-run]` — bring the board current: regenerate the guide,',
  '  baseline, and views, and reconcile any structural drift the new version implies.',
  '  Idempotent, and it never touches your manifest, cards, or prose. Use it rather',
  '  than `init` — `init` *creates* a board, `upgrade` refreshes one.',
  '',
  'Commit the board first (`manifest` + `events.jsonl` are the durable truth; `views/`',
  'regenerate) so the refresh is recoverable. This is the tactical layer — the',
  'evolution that matters is the process work above.',
  '',
].join('\n');
