import { refEdges, refTarget, collectBacklinks } from './refs.js';

// A record's resolved graph view, rendered to markdown — the materialized view kanbento
// OWNS (a side-car), so the source file stays human-definitive and untouched. Backlinks
// are inverse edges (computed from other files) and cannot live in the source; this is
// their only honest home. Like BOARD.md, but per record: refresh on demand, `refs` is
// the live truth. Pure — { exists } is injected for path/file: resolution.

const q = (s) => `"${s ?? ''}"`;

function mark(t, known, exists) {
  if (!t.known) return '⚠ unknown type';
  if (t.type === 'file') return exists && !exists(t.path) ? '⚠ missing' : '✓';
  if (t.embodiment === 'none') return '~ handle';
  return known.has(t.curie) ? '✓' : '⚠ dangling';
}

export function renderMap(record, { cards = [], records = [] }, manifest, { exists, sinceVerified } = {}) {
  const known = new Set(records.map((r) => r.curie).filter(Boolean));
  const lines = [`# ${record.curie ?? record.path}${record.status ? `  [${record.status}]` : ''}`, ''];
  lines.push(`<!-- generated by \`kanbento map\` — do not edit. source: ${record.path} -->`, '');

  if (record.parent) lines.push(`↑ part-of  ${record.parent}`, '');

  const kids = records.filter((r) => r.parent === record.curie);
  if (kids.length) {
    lines.push(`↓ children (${kids.length})`);
    for (const k of kids) lines.push(`    ${k.curie}${k.status ? ` [${k.status}]` : ''}  ${q(k.title)}`);
    lines.push('');
  }

  const { groups, total } = collectBacklinks({ cards, records }, record.curie, {});
  lines.push(`← backlinks (${total})`);
  for (const g of groups) {
    lines.push(`  ${g.rel}`);
    for (const s of g.sources) lines.push(`    ${s.kind === 'card' ? 'card   ' + s.ref.slice(0, 8) : 'record ' + s.ref}  ${s.state ?? ''}  ${q(s.title)}`);
  }
  if (!total) lines.push('  (none)');
  lines.push('');

  const fwd = refEdges(record.refs);
  if (fwd.length) {
    lines.push('→ refs');
    for (const e of fwd) lines.push(`  ${e.rel}  ${e.curie}  ${mark(refTarget(manifest, e.curie), known, exists)}`);
    lines.push('');
  }

  // The curation inspect block: for a git-verified record with a footprint, the commits
  // that touched that footprint since `verified:` — the evidence to weigh before choosing
  // reaffirm vs revise. Pure: `sinceVerified` is injected ({ sha, commits[], more }); the
  // CLI runs `git log` (fail-soft, capped) and the renderer just lays it out.
  const iv = sinceVerified?.(record);
  if (iv && iv.commits?.length) {
    lines.push(`⟳ since verified (git:${iv.sha.slice(0, 7)})`);
    for (const c of iv.commits) lines.push(`  ${c}`);
    if (iv.more) lines.push(`  … +${iv.more} more`);
    lines.push('');
  }

  return lines.join('\n').replace(/\n+$/, '\n');
}

// The stamps × refs aggregation both the footprint and curation read-models fold over:
// per record CURIE, the union of worktree paths stamped on lifecycle events of the cards
// that ref it (any relation key — the fold already honored CardUnlinked retractions, so a
// card's refs are its live edges), each path carrying how many events touched it and which
// cards contributed. Returns curie -> Map(path -> { count, cards:Set }). Never stored —
// always regenerable from the log. Pure.
export function recordFootprints(records, cards, events) {
  const stampsByCard = new Map(); // cardId -> [ dirty[], ... ] (one entry per stamped event)
  for (const e of events) {
    if (!e?.worktree || !e.cardId) continue;
    const arr = stampsByCard.get(e.cardId) ?? [];
    arr.push(Array.isArray(e.worktree.dirty) ? e.worktree.dirty : []);
    stampsByCard.set(e.cardId, arr);
  }
  const out = new Map();
  for (const r of records) {
    if (!r.curie) continue;
    const refing = cards.filter((c) => Object.values(c.refs ?? {}).flat().includes(r.curie));
    const agg = new Map(); // path -> { count, cards:Set }
    for (const c of refing) {
      for (const dirty of stampsByCard.get(c.id) ?? []) {
        for (const p of dirty) {
          const e = agg.get(p) ?? { count: 0, cards: new Set() };
          e.count += 1;
          e.cards.add(c.handle);
          agg.set(p, e);
        }
      }
    }
    out.set(r.curie, agg);
  }
  return out;
}

// The footprint read-model — each record's code footprint, derived from the worktree
// stamps in the log. Pure; paths sorted by count desc then name; records with no stamps
// are skipped.
export function renderFootprints(records, cards, events) {
  const footprints = recordFootprints(records, cards, events);

  const lines = [
    '# Footprints',
    '',
    '<!-- generated by `kanbento map` — do not edit. derived from worktree stamps in the log; always regenerable. -->',
    "Each record's code footprint: the worktree paths stamped on lifecycle events of the cards that ref it. `path · N× · cards` — N is how many events touched the path. Refresh with `kanbento map`.",
    '',
  ];

  const sections = [];
  for (const r of records) {
    if (!r.curie) continue;
    const agg = footprints.get(r.curie) ?? new Map();
    if (!agg.size) continue; // no stamps reach this record — nothing to project
    const rows = [...agg.entries()].sort((a, b) => b[1].count - a[1].count || (a[0] < b[0] ? -1 : 1));
    const s = [`## ${r.curie}${r.title ? `  ${q(r.title)}` : ''}`, ''];
    for (const [p, info] of rows) s.push(`- ${p}  ·  ${info.count}×  ·  ${[...info.cards].sort().join(', ')}`);
    s.push('');
    sections.push(s.join('\n'));
  }

  if (!sections.length) lines.push('(no stamped footprints yet)', '');
  else lines.push(sections.join('\n'));
  return lines.join('\n').replace(/\n+$/, '\n');
}

// The curation read-model — records ranked by churn-since-verified (commits touching a
// record's footprint since its `verified:` sha), worst first, so the stalest worldview
// tops the revision queue. Below the ranked list, two visible buckets keep the queue's
// tail honest rather than invisible: records with a footprint but never verified, and
// records with no footprint (no ground to measure). Pure: `churn(curie)` is the injected
// git-backed count (the CLI runs `git rev-list`); the renderer owns bucketing, orphan
// flags, and the calendar clocks. Non-git / date-verified scope degrades to n/a.
export function renderCuration(records, cards, events, { churn } = {}) {
  const footprints = recordFootprints(records, cards, events);
  const churnOf = typeof churn === 'function' ? churn : (c) => churn?.[c];

  const rows = [];
  for (const r of records) {
    if (!r.curie) continue;
    const size = footprints.get(r.curie)?.size ?? 0;
    const stamp = typeof r.verified === 'string' ? r.verified : null;
    const gitStamp = stamp?.startsWith('git:') ?? false;
    const c = gitStamp && size ? churnOf(r.curie) : null;
    // The FS tree carries part-of by design ("the tree carries the taxonomy, refs
    // carry the cross-cutting graph"), so a nested record — one with a tree parent, or
    // one that parents children — is NOT disconnected. Count that tree edge alongside
    // refs + backlinks; only a record with none of the three is a true orphan.
    const hasTreeEdge = r.parent != null || records.some((x) => x.parent === r.curie);
    const orphan = !hasTreeEdge && refEdges(r.refs).length === 0 && collectBacklinks({ cards, records }, r.curie, {}).total === 0;
    rows.push({
      curie: r.curie,
      verified: stamp,
      // js-yaml parses a bare `revised: 2026-07-05` as a Date — normalize both forms
      revised: r.revised instanceof Date ? r.revised.toISOString().slice(0, 10) : typeof r.revised === 'string' ? r.revised : null,
      size,
      orphan,
      churn: Number.isFinite(c) ? c : null,
    });
  }

  const ranked = rows.filter((r) => r.size && r.verified) // has footprint + a verified stamp: churn-rankable (n/a for date/no-git)
    .sort((a, b) => (b.churn ?? -Infinity) - (a.churn ?? -Infinity) || (a.curie < b.curie ? -1 : 1));
  const neverVerified = rows.filter((r) => r.size && !r.verified).sort((a, b) => (a.curie < b.curie ? -1 : 1));
  const noFootprint = rows.filter((r) => !r.size).sort((a, b) => (a.curie < b.curie ? -1 : 1));

  const verifiedCell = (v) => (v ? (v.startsWith('git:') ? `git:${v.slice(4, 11)}` : v) : '—');
  const row = (r) => `| ${r.curie} | ${verifiedCell(r.verified)} | ${r.churn == null ? 'n/a' : r.churn} | ${r.revised ?? '—'} | ${r.size} | ${r.orphan ? 'orphan' : ''} |`;
  const table = (rs) => (rs.length
    ? ['| record | verified | churn | revised | footprint | orphan |', '| --- | --- | --- | --- | --- | --- |', ...rs.map(row)]
    : ['(none)']);

  const lines = [
    '# Curation',
    '',
    '<!-- generated by `kanbento map` — do not edit. derived from `verified:`/`revised:` stamps, footprints, and git churn; always regenerable. -->',
    "Records ranked by churn-since-verified — commits touching a record's footprint since its `verified:` sha, worst first. Then records with a footprint but never verified, then records with no footprint (no ground to measure). Churn is n/a for date-verified or non-git scope. Refresh with `kanbento map`.",
    '',
    '## ranked by churn-since-verified',
    ...table(ranked),
    '',
    '## never verified (has footprint)',
    ...table(neverVerified),
    '',
    '## no footprint',
    ...table(noFootprint),
    '',
  ];
  return lines.join('\n').replace(/\n+$/, '\n');
}

// The home page for the materialized maps — a navigable index so an agent discovers
// the knowledge graph at all. Records grouped by type, each laid out as its folder
// taxonomy (roots, children indented), linking to the record's map.
export function renderMapIndex(records, manifest) {
  const lines = [
    '# Knowledge map',
    '',
    '<!-- generated by `kanbento map` — do not edit. -->',
    'The records and their resolved graph. Refresh with `kanbento map`; `kanbento refs <curie>` is the live query.',
    '',
  ];
  const byType = new Map();
  for (const r of records) { const k = r.type ?? 'untyped'; (byType.get(k) ?? byType.set(k, []).get(k)).push(r); }
  for (const [type, recs] of [...byType.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    lines.push(`## ${type} (${recs.length})`, '');
    const curies = new Set(recs.map((r) => r.curie));
    const byParent = new Map();
    for (const r of recs) { const p = r.parent && curies.has(r.parent) ? r.parent : null; (byParent.get(p) ?? byParent.set(p, []).get(p)).push(r); }
    const emit = (parent, depth) => {
      for (const r of (byParent.get(parent) ?? []).sort((a, b) => ((a.curie ?? a.path) < (b.curie ?? b.path) ? -1 : 1))) {
        lines.push(`${'  '.repeat(depth)}- [${r.curie ?? r.path}](${r.path})${r.status ? ` — ${r.status}` : ''}`);
        emit(r.curie, depth + 1);
      }
    };
    emit(null, 0);
    lines.push('');
  }
  return lines.join('\n').replace(/\n+$/, '\n');
}
